#!/usr/bin/env node
var resource = require('resource'),
    config = require('../../config'),
    debug = require('debug')('alert'),
    uuid = require('node-uuid'),
    http = require('resource-http'),
    view = require('view'),
    bitcoin = require('bitcoin'),
    wallet = require('../../lib/resources/wallet'),
    user = require('../../lib/resources/user'),
    metrics = require('../../lib/resources/metrics').metrics,
    vault = require('../../lib/resources/vault').vault;

wallet.persist(config.datasource);
metrics.persist(config.datasource);

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

console.log('getting daily totals');
vault.getBalance(function(err, balance){
  wallet.all(function(err, _wallets){
    console.log('creating metrics');
    metrics.create({
      bitcoin: balance.totals.bitcoin.amount,
      peercoin: balance.totals.peercoin.amount,
      dogecoin: balance.totals.dogecoin.amount,
      dollars: balance.total,
      wallets: _wallets.length
    }, function (err, res){
      if (err) {
        throw err;
      }
      console.log('saved metrics', res);
    });
  });
});