#!/usr/bin/env node
var resource = require('resource'),
    config = require('../../config'),
    debug = require('debug')('alert'),
    uuid = require('node-uuid'),
    wallet = require('../../lib/resources/wallet'),
    metrics = require('../../lib/resources/metrics').metrics,
    prices = require('../../lib/resources/prices').prices,
    vault = require('../../lib/resources/vault').vault;

wallet.persist(config.datasource);
metrics.persist(config.datasource);
prices.persist(config.datasource);

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

debug('getting daily totals');
vault.getBalance(function(err, balance){
  wallet.all(function(err, _wallets){
    debug('creating metrics');
    metrics.create({
      bitcoin: balance.totals.bitcoin.amount,
      litecoin: balance.totals.litecoin.amount,
      peercoin: balance.totals.peercoin.amount,
      dogecoin: balance.totals.dogecoin.amount,
      dollars: balance.total,
      wallets: _wallets.length
    }, function (err, res){
      if (err) {
        throw err;
      }
      debug('saved metrics', res);
    });
  });
});